### ISSUE TITLE
[BUG] Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by Sa7aR-Kassem** [TDRA-ae/aegov-dls#67] opened 2024-11-20 01:13 UTC
Take a moment to review - is it really a bug? Or is it more of an enhancement or a typo in the documentation? A **Bug** is code that is broken, or when you try to implement a certain piece of code that is mentioned in the documentation, you have a result that is not the same as described. 

Now if you are absolutely sure it is indeed a bug, please fill in the following template.

---

**Mention what part of the design system the bug is related to**
Is the bug part of a "Component", a "Block", the "Plugin" itself or something else? Ideally, your choice has to be one of the 3 items.

**More context in relation to the design system**
If the bug is part of a component or a block, please mention which one. If the bug is related to the plugin, please mention if it is during installation, compiling or configuration.

**Describe the bug**
A clear and concise description of what the bug is. Help us understand what you are doing that is causing an error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use chrome lighthouse tool
2. Analysis the page 
3. Report  has an error does not use passive listeners to improve scrolling performance
4. Consider marking your touch and wheel event listeners as passive to improve your page's scroll performance ` designsystem.min.js`. [Learn more about adopting passive event listeners](https://developer.chrome.com/docs/lighthouse/best-practices/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools).

**Expected behaviour**

**A bit more context about the browser**

**Additional context**

**Comment by moiz-conceptlz** [comment] 2024-11-20 06:20
@Sa7aR-Kassem 

Are you sure you are testing Lighthouse for your website in an incognito mode, and there are no chrome plugins added?

Are you referring to the JS code of aegov-scripts or to the custom code that you have added?

Passive listeners as a warning or error would be added to "Best Practices" section of Lighthouse. I'm attaching a screenshot of a website in incognito mode, with no chrome plugins added, tested from within the UAE, using version 2.2.5 of the design system. There is no such reported issue of Passive Listeners.

<img width="2075" alt="Screenshot 2024-11-20 at 10 17 11 AM" src="https://github.com/user-attachments/assets/bb78242d-c929-4dbc-a663-7a75ab97f7d3">

**Comment by moiz-conceptlz** [comment] 2024-11-25 06:36
Closing this as this is not a bug

**Closed by moiz-conceptlz** 2024-11-25 06:36 UTC
Labels: not a bug
